apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-nh-1552001178:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-nh-1552001178:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-nh-1552001178
        chartPath: charts/bdd-nh-1552001178
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-nh-1552001178'
          image.tag: '{{.DIGEST_HEX}}'
